# Generated by Django 5.0.2 on 2024-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='serviciotarot',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
