# Generated by Django 5.0.2 on 2024-03-10 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_alter_pregunta_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
